<template>
  <div class="max-w-2xl space-y-4 text-sm text-slate-700">
    <h2 class="text-xl font-bold text-slate-800">About</h2>
    <p>
      This dashboard visualizes the
      <a
        href="https://www.kaggle.com/datasets/iamsouravbanerjee/house-rent-prediction-dataset"
        target="_blank"
        class="text-indigo-600 underline hover:text-indigo-800"
      >House Rent Prediction Dataset</a>
      from Kaggle — Indian residential listings with rent, size, BHK count, city, and furnishing details.
    </p>
    <p>
      The backend runs a linear regression of Rent on Size for the filtered slice and exposes the results
      via a FastAPI REST API. The AI insight is generated by Google Gemini based on the regression statistics.
    </p>
    <p class="text-xs text-slate-400">Stack: Vue 3 · Pinia · Chart.js · FastAPI · SQLite · Google Gemini</p>
  </div>
</template>
